### ISSUE TITLE
Not able to install on Debian 11 stable 

### ISSUE THREAD

**Issue by jamess60** [et0ndyy/Win2k#1]
Hi

I just tried installing on Debian 11 stable, fully up to date, but I was unable. 
Initially the xfce4-panel-profiles package was missing and not able to be installed - installing xfce4-goodies did not remedy this. 

The script gave 3 dpkg errors for the .deb files in lib/, then gave the Y/N prompt for the greeter.

**Comment by et0ndyy** [comment]
Hello there,
xfce4-panel-profiles package can be build from source and downloaded from: https://docs.xfce.org/apps/xfce4-panel-profiles/start
If its not in your repository. Just follow the instructions to install.
I tested the script in Ubuntu based OS like linux mint, if errors exist from the script that means some packages are not installed or missing from your repo and need to download them from the internet or add the repos to your source list.
The Y/N prompt for the greeter, means that it will replace your greeter with lightdm-greeter in order to customize it further with the Windows 2000 theme.

**Comment by et0ndyy** [comment]
You can also look here https://packages.debian.org/sid/xfce4-panel-profiles to install the requirements.
The only purpuse of the script is to install the package requirements, If it fails you can install them manually.

**Comment by jamess60** [comment]
I did try the SID version but that also wouldnt install, tried building the package from source and it fails on other dependencies which also arent avaliable. 

Looks like im running XFCE 4.16 which appears to be supported.

**Comment by et0ndyy** [comment]
xfce4-panel-profiles needed only to load the theme of the taskbar. You can recreate your own taskbar based on the profile, if you cant install xfce4-panel-profiles. Also check this video: https://www.youtube.com/watch?v=HLauAQm3EEE
 to try something similar in order to install xfce4-panel-profiles.
